Volume Path 를 통해 Dicom Volume 을 캐시로 다운로드 받고 Image 를 화면에 출력하기
hsskia/unity_task pull request #10
Opened 2024-03-28 02:07 UTC by hsskia

close #9 

### Process
- seriesID 와 일치하는 dicom volume 캐시로 불러오기
  - 이미 존재한다면 존재하는 volume 사용하기
- normalized 된 배열을 사용해 이미지를 화면에 출력하기
- Slider 로 이미지 index 를 바꿔가며 볼 수 있도록 기능 추가하기

2024-03-28 05:21 UTC, DaesooYoon-Skia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            Debug.Log($"Dicom Series ID {seriesId} 의 Volulme 파일은 존재하지 않습니다.");
Volume

2024-03-29 01:34 UTC, alkee-skia commented
언제든지 새로 받을 수 있는 nuget package 파일들은 version 관리 대상이 아닙니다. 이를 관리하는 설정만 버전관리(repository 에 포함) 하시면 됩니다. version 관리되지 않아야 하는 파일을 구분해주시고 .gitignore 등을 이용해 다시 구성해봐주세요.

2024-03-29 03:43 UTC, alkee-skia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        List<string> searchIdList = new List<string>();
type 이 선언되어있는 변수에 new 할당 하는경우 type 을 반복지정할 필요 없이 축약가능합니다. vscode 사용시 점선 밑줄이 나타나는 곳들을 보시면 코드 수정에 대한 제안이 뜰테니 한번씩 확인해봐주시면 좋겠습니다.

2024-03-29 05:58 UTC, hsskia commented
피드백 감사합니다 과장님!

Rebase 통해서 gitignore 작성 이전, 버전관리에 nuget 패키지들이 포함됐던 부분 삭제했고 gitignore 에는 버전관리에 포함되지 않아야 하는 파일들이 이미 작성 되어있었는데 gitignore 작성 이전에 commit 한 파일들이 File changed 항목에 나타난 것 같습니다.

아래 이미지에 있는 Nuget 은 unity 빌드시 다른 패키지들을 설치하기 위해 포함이 되어야하는데 과장님이 버전관리에서 분리해달라고 말씀하신 부분이 이 부분이실까요?
![image](https://github.com/hsskia/unity_task/assets/162946806/4246cf5a-2c0e-4d28-8301-f9cb21ff8fbe)

아니면 위에서 제가 삭제한 부분이 맞을까요?

2024-03-29 07:06 UTC, alkee-skia commented
> 아래 이미지에 있는 Nuget 은 unity 빌드시 다른 패키지들을 설치하기 위해 포함이 되어야하는데 과장님이 버전관리에서 분리해달라고 말씀하신 부분이 이 부분이실까요?

일단 제가 comment 남긴 것은 nuget plugin 이 아닌 이 plugin 을 이용해 재구성 가능한 파일들을 보고 남긴것이었습니다. 그리고 nuget plugin 도 [GlitchEnzo/NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity)를 사용하신다면 README 에서 보이는대로 unity package manager 를 이용해 등록하는 경우 (아래 이미지) 이 조차도 제거할 수 있기는 합니다. (`manifest.json` 파일을 통한 추가)

<img width="867" alt="스크린샷 2024-03-29 16 04 17" src="https://github.com/hsskia/unity_task/assets/49409100/0ab10d11-b3a9-4f32-b251-a3b35da761d7">

2024-03-29 08:35 UTC, hsskia commented
과장님 피드백 정말 감사합니다!
`manifest` 에 NuGet 추가해서 plugin 도 관리 할 필요가 사라졌습니다.

추가로 dependencies 에 NuGet github 링크를 추가할 때 Readme 에 보이는 방식으로는 인식을 하지 못해
```
"com.github-glitchenzo.nugetforunity": "https://github.com/GlitchEnzo/NuGetForUnity.git?path=/src/NuGetForUnity",
```
다음과 같은 방식으로 해결했습니다!
[참고 github](https://github.com/ChartBoost/chartboost-mediation-unity-sdk)

2024-04-04 04:58 UTC, hyunheeskia requested changes
![image](https://github.com/hsskia/unity_task/assets/134245511/b5f501aa-44d5-4b23-b299-faf81d7d2301)

dicom study 를 두 번 클릭하면 가장 첫번째 dicom series 의 text 가 "Button" 으로 변하는 버그가 있습니다.

2024-04-04 07:29 UTC, hyunheeskia commented
DicomTableView class 의 네이밍을 DicomImageViewer 로 변경하셨는데,
제가 추측하기로는 현승씨가 생각하시기에 TableView 보다는 ImageViewer 라는 기능을 더 중요한 기능으로 생각하신 것 같습니다.

제가 보기에도 ImageViewer 로써의 기능이 중요해 보이긴 합니다만,
TableView 가 아니라고 하기도 어려울 것 같아요.

그래서 제가 제안드리는 방법은
가능하면 기능 단위로 분리하는 연습을 해보셨으면 해서
기존의 DicomTableView 에서 DicomImageViewer 로써의 기능을 분리해서
별도 class 로 만드는 방식으로 해보시면 좋을 것 같습니다.

그리고 별개로,
class 이름은 바뀌었는데 cs 파일 이름은 그대로라서 매칭이 되지 않네요 ㅎㅎ

2024-04-05 01:05 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/DicomTableview.cs
> +        volumeSlider.maxValue = slices - 1; // slice 의 index 가 0부터 시작했기 때문에 -1
이 주석은 굳이 넣지 않아도 될 듯 합니다
위의 slider 시작 지점이 항상 index 0 이 되도록 설정 이라는 주석으로도 충분할 듯 해서요~

2024-04-05 01:05 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/DicomTableview.cs
> +    private readonly Dictionary<string, string> dicomIdVolumePathDict = new();
Dict 는 굳이 붙이지 않아도 될 듯 합니다. 
이름만 너무 길어지는 것 같아서요 그리고 타입 보면 알 수 있으니..

dicomIdVolumePaths 로 하면 위의 dictionary 들과 통일성 있을 듯 하네요

2024-04-05 06:10 UTC, hyunheeskia requested changes

2024-04-05 06:10 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +        void OnSliderValueChanged(float sliderValue, Texture2D volumeTexture, Dictionary<int, Color[]> slicedColors)
slicedColors 는 불필요하게 전달되는것으로 보입니다.
Texture2D 만으로도 파라미터는 충분할것같습니다.

2024-04-05 06:59 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +        void OnSliderValueChanged(float sliderValue, Texture2D volumeTexture, Dictionary<int, Color[]> slicedColors)
```csharp
void SetVolumeImage(int sliceNumber, int width, int height, Dictionary<int, Color[]> slicedColors)
{
      Texture2D volumeTexture = new(width, height);
      volumeTexture.SetPixels(slicedColors[sliceNumber]);
      volumeTexture.Apply();
      volumeImage.texture = volumeTexture;
}
```

이 함수로 중복 부분 대체했습니다! 감사합니다.

2024-04-08 00:56 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +        public void SetVolumeVisible(bool volumeVisible)
이거는 그냥 궁금해서 물어보는건데요,
DicomImageViewer 가 volumeImage 와 volumeSlider 로만 구성된 것으로 보이는데,
둘 다 SetActive 하는것이면
DicomImageViewer 자체를 SetActive 하는것과 같은 것 아니에요?

2024-04-08 01:40 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +        public void SetVolumeVisible(bool volumeVisible)
맞습니다. DicomImageViewer 자체를 SetActive 하는 것과 같은데 DicomImageViewer 로 접근해서 비활성화 시키려면 DicomImageViewer 가 연동된 volumeContent 라는 GameObject 에 접근하기 위해 `[SerializeField] private GameObject volumeContent` 등과 같은 코드를 추가해야 합니다. 그래서 굳이 script 에 등장하지 않는 새로운 object 로 접근을 하지 않으려고 이미 접근해서 사용해야 했던 image 와 slider 를 사용하여 visibility 를 조정했습니다.

2024-04-08 01:43 UTC, hyunheeskia requested changes

2024-04-08 01:43 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        dicomSeriesButtonsData[seriesData] = new List<string> { dicomSeries.id.ToString(), dicomSeries.volumeFilePath };
id 와 file path 가 둘 다  string 으로 데이터 타입이 같다 하더라도
List 로 묶으면서 속성이 다르다면 사용하는 쪽에서 알아차리기는 힘들것같습니다.
차라리 Tuple 로 묶는 것이 좋아보입니다.

2024-04-08 08:11 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +        public void SetVolumeVisible(bool volumeVisible)
object 활성화만을 위해서 `SetVolumeVisible` 함수를 만드는 것보다 volumeContent 에 접근해서 image 와 slider 를 제어하는 것이 더 효율적이라고 생각돼서 코드 수정했습니다.

2024-04-09 01:23 UTC, hyunheeskia commented
(volumeContent 라든지) 처음 시작할 때는 없어도 되는 구성요소들이 처음부터 scene 에 존재하도록 만들어져 있는데,
prefab 이라는 것을 써보시면 어떨까 합니다.
물론 안 써도 크게 상관은 없지만,
작은 수정을 했을 때 scene conflict 도 방지해줄거고,
연습하는거니까 한번 써보시면 좋을것같습니다.
일단 prefab 이 뭔지 찾아보시고,
무엇을 prefab 으로 만들어야 할지는
현민씨가 이미 쓰고있으니 함 물어보시는것도 좋을것같아요.

2024-04-09 07:48 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        Button seriesDataButton = EventSystem.current.currentSelectedGameObject.GetComponent<Button>();
차라리 button 에 OnClick 이벤트를 다는 방법은 어떨까요?

2024-04-09 07:49 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        Button seriesDataButton = EventSystem.current.currentSelectedGameObject.GetComponent<Button>();
아 다시 보니까 AddListener 가 되어있네요. currentSelectedGameobject 를 이용하지 않는 다른 방법은 없을까요? 뭔가 불필요하게 한 단계를 더 거치는 느낌이어서요.

2024-04-09 08:42 UTC, hsskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        Button seriesDataButton = EventSystem.current.currentSelectedGameObject.GetComponent<Button>();
버튼이 클릭되었을 때 클릭된 `현재 버튼`을 통해 Dicom 정보가 저장된 Dictionary 에 접근하기 때문에 필수적인 단계가 될 것 같습니다!

2024-04-09 08:43 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        Button seriesDataButton = EventSystem.current.currentSelectedGameObject.GetComponent<Button>();
넵!

2024-04-09 08:46 UTC, hyunheeskia approved these changes

2024-04-11 02:38 UTC, ChoiSieun1 approved these changes

2024-04-11 04:16 UTC, YunKeonTeck approved these changes

2024-04-11 04:43 UTC, alkee-skia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +                slicedColors[i] = slicedImageColor;
key 가 index 이므로 index 를 즉시 access 할 수 있는 array 나 list 가 더 알맞은 data structure 일 것 같습니다.

2024-04-11 04:43 UTC, alkee-skia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            SetVolumeImage(0, width, height, slicedColors);
코드를 보니, member 가 아닌 local 변수인데 0 번째 slice 만 사용하네요? 과제 영역 때문인 것인지 모르곘습니다만 첫번째 slice 만 사용하는데 전체 데이터(slicedColors)를 모두 설정해두신 이유가 무엇일까요?

2024-04-11 05:08 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            SetVolumeImage(0, width, height, slicedColors);
slider 를 조작하기전(이미지가 처음 화면에 띄워졌을때)에도 이미지를 출력하기 위해 가장 첫번째 slice 인 index 0으로 초기 이미지를 띄웁니다. 

초기 이미지를 띄운 후에는 
```csharp
volumeSlider.onValueChanged.AddListener((value) => SetVolumeImage((int)value, width, height, slicedColors));
```
위의 코드에서 슬라이더를 움직일 때마다 index 에 맞는 이미지가 출력됩니다.

2024-04-11 05:09 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +                slicedColors[i] = slicedImageColor;
해당 부분 수정하겠습니다!

2024-04-11 05:35 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            SetVolumeImage(0, width, height, slicedColors);
과장님 말씀처럼 slicedColors 전체를 전달하는 것이 아니라 index 에 알맞은 data 만 전달하도록 수정할 수 있을 것 같습니다.

```csharp
SetVolumeImage(width, height, slicedColors[0]);
...
volumeSlider.onValueChanged.AddListener((value) => SetVolumeImage(width, height, slicedColors[(int)value]));
```

2024-04-12 02:42 UTC, alkee-skia requested changes

2024-04-12 02:42 UTC, alkee-skia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            volumeSlider.onValueChanged.AddListener(delegate { ApplyVolumeImage(); });
ShowSlice 동작과 맞지 않는 (ui control 에 이벤트 설정) 것 같습니다. 이 위 코드들은 초기화와 관련된 것 같은데요?
`onValueChanged` 같은 경우 show 할 때마다(보여질 때 마다?) event listener 가 추가 등록되어 문제가 될 것 같습니다. 
이 개체의 최초 설정에만 적용하려면 awake/start 에, 명시적인 setup 시에 설정을 하고자한다면(동적인 정보가 필요한 경우) setup 시에(재사용-재호출 될 수 있으므로 remove all listener 와 함께) 설정되어야 할 것 같습니다.

2024-04-12 02:42 UTC, alkee-skia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            if (file != "")
file 이 공백인 경우는 어떤 경우인가요? 실제로 발생하는 경우라면 알아차릴 수 있는 방법(최소한 로깅)이 필요하고, 제가봐서는 발생하면 안되는 상황일 것 같은데 이런 경우라면 Debug.Assert 정도로 단순화 시키면 될 것 같습니다.

2024-04-12 05:13 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            volumeSlider.onValueChanged.AddListener(delegate { ApplyVolumeImage(); });
`onValueChanged` 는 최초 설정에만 적용하도록 start 함수를 추가했고 불필요한 초기화 코드는 삭제했습니다. maxValue 는 기존에 `Setup` 이란 함수를 `SetupImageAndSlider` 라는 이름으로 변경하여 slider 설정에 필요한 코드를 추가했습니다.

2024-04-12 05:15 UTC, hsskia commented on Task1/Assets/Scripts/DicomImageViewer.cs
> +            if (file != "")
실제로 존재하는 volume data 만 load 하기위해 file path 에 null 값이 발견되었을 시점에 '파일이 없다' 라는 경고 문구가 출력되도록 변경했습니다.

2024-04-12 05:18 UTC, hsskia commented
Axial 뿐만 아니라 Coronal, Sagittal Plane 도 띄우도록 추가하겠습니다!

2024-04-16 02:16 UTC, hyunheeskia approved these changes

2024-04-17 06:51 UTC, ChoiSieun1 approved these changes

2024-04-22 00:48 UTC, YunKeonTeck approved these changes

2024-04-22 02:39 UTC, merged