ORM 파일을 사용해서 서버에서 DICOM 데이터를 받아와 Unity 콘솔에 출력하기
hsskia/unity_task pull request #2
Opened 2024-03-14 08:22 UTC by hsskia

close #1 

### 발생한 이슈와 해결 방안
- 이슈1. 서버에서 데이터를 받아왔을 때 UnityWebRequest의 downloadHandler.text attribute를 사용하면 string 형식으로 데이터가 저장되어 Parsing에 어려움이 있음.
  - Newtonsoft.Json 패키지를 설치하여 text 데이터를 JArray 형태로 변환 후 Parsing

- 이슈2. Orm.cs 파일의 sqlite 패키지 로딩시 에러 발생
  ```
  Assets\Orm.cs(3,7): error CS0246: The type or namespace name 'SQLite' could not be found (are you missing a using 
  directive or an assembly reference?)
  ```
  - nuget 패키지 설치 후 sql-net-pcl 라이브러리를 설치하여 문제 해결
 
### 코드 작성 흐름
1) ORM 파일 사용없이 Web에서 데이터를 불러서 json 형태로 변환되는지 확인
2) 서버와 통신이 되는 것을 확인하고 JArray 포멧을 활용하여 ORM 내에 있는 DicomStudy와 DicomSeries class 생성
3) DicomStudy 데이터를 출력 후 study id와 일치하는 DicomSeries 데이터 출력(출력 결과 아래 이미지 참고)

### Output
- Unity console 출력 내용
  ![image](https://github.com/hsskia/unity_task/assets/162946806/207adcc5-2c51-4ac9-9160-3e4fa80dbecb)

- 세부 출력 내용
  - Dicom Study Data
  ![image](https://github.com/hsskia/unity_task/assets/162946806/6c3c8438-a5ee-42a4-bdec-7a90f9688f7d)

  - Dicom Series(Dicom Study ID와 연동된 Series Data)
  ![image](https://github.com/hsskia/unity_task/assets/162946806/5a49d9d2-b7c1-407d-ac07-371f499d7b05)

2024-03-15 00:08 UTC, hyunheeskia requested changes

2024-03-15 00:08 UTC, hyunheeskia commented on Task1/Assets/Scripts/orm_get_dicom.cs
> +    void MakeDicomStudy(JObject data){
함수 이름과 동작은 맞추는 게 좋을것같습니다.
함수의 주된 내용이 출력이라면 make 보다는 print 가 어떨까 합니다.

2024-03-15 00:08 UTC, hyunheeskia commented on Task1/Assets/Scripts/orm_get_dicom.cs
> +    void MakeDicomStudy(JObject data){
함수 이름이 PrintDicomStudy 가 된다면 함수 이름만 보고도 주석에 작성하신 "DicomStudy 출력 함수" 임을 알 수 있기 때문에 굳이 주석을 달 필요도 없어집니다.

2024-03-15 00:37 UTC, hyunheeskia approved these changes

2024-03-15 02:19 UTC, alkee-skia commented
Packages 경로는 nuget 으로 다시 구성될 수 있습니다. 따라서 어떤 pakcage 가 설치되어야 하는지를 정하는 구성파일만 버전관리 되면 됩니다. 이처럼, 버전관리되어야 하는 파일과 그렇지 않은 파일들을 구분해 주시면 좋겠습니다.

2024-03-15 06:47 UTC, hsskia commented
피드백 감사합니다 과장님ㅎㅎ

2024-03-18 02:18 UTC, ChoiSieun1 requested changes

2024-03-18 02:18 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/orm_get_dicom.cs
> +        string res = "Dicom Study Data \n";
res 라고 하는 것보단 result 이런식으로 풀네임을 변수로 써주시는게 다른 사람들이 코드 보기 편할 것 같습니다.

2024-03-18 02:18 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/orm_get_dicom.cs
> +        string res = "Dicom Study Data \n";
아래에도 이와 같은 네이밍이 보이는데 같이 수정해주세요~

2024-03-18 02:18 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/orm_get_dicom.cs
> +        UnityWebRequest req_study = UnityWebRequest.Get("http://10.10.20.173:5080/v2/Dicom/Study");
server 주소를 따로 string 으로 빼서 사용하는건 어떤가요?

2024-03-18 02:18 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/orm_get_dicom.cs
> +                UnityWebRequest req_series = UnityWebRequest.Get("http://10.10.20.173:5080/v2/Dicom/Series?studyId="+ item["id"]);
여기서도 string 으로 따로 빼서 사용해도 좋을 듯 합니다.
위의 서버 주소와 여기의 서버 주소의 공통부분을 변수로 하고, 뒤를 붙여서 사용해도 좋을 듯 하네요

2024-03-18 02:27 UTC, ChoiSieun1 requested changes

2024-03-18 02:27 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/orm_get_dicom.cs
> +public class dicom_test : MonoBehaviour
dicom_test 라고 네이밍짓기 보단 음... test 는 우선 빼는 게 좋을 것 같습니다
dicom data 를 read 하고 print 하는 거와 관련된 이름이면 좋을 듯 합니다. 
혹시 다른분들 좋은 의견 있으시면 댓글 남겨주세요

2024-03-19 01:41 UTC, ChoiSieun1 approved these changes

2024-03-19 09:03 UTC, YunKeonTeck approved these changes

2024-03-20 01:21 UTC, merged