Dicom Data 를 Unity UI 에 TableView 로 출력하기
hsskia/unity_task pull request #4
Opened 2024-03-19 08:05 UTC by hsskia

close #3 close #7

### 발생한 이슈와 해결 방안
- 이슈1. Text Object 만을 사용하여 Dicom Data 를 표현하면 text 가 잘리는 현상 발생
  -  ScrollView Object 를 사용하여 데이터의 길이에 따라 UI 가 유연하게 동작하도록 설정

- 이슈2. 스크립트에서 object 변수 생성 시 `NullReferenceException`  에러 발생
  ```
  NullReferenceException: Object reference not set to an instance of an object
  ```
  - Inspector 에 object 를 정확히 할당시키고 그럼에도 에러 발생 시 다른 object 의 Inspector 에 스크립트가 잘못 추가되어 에러가 발생하고 있진 않은지 확인 필요
 
### 코드 작성 흐름
1) Canvas 에 구성해놓은 Object 들의 관계 설정(부모, 자식 관계)
2) 각 object 에 일치하는 Dicom study data 매칭
3) Dicom study 의 ID 값을 클릭하면 일치하는 Dicom study data 밑에 Dicom series data 가 출력
4) Dicom study 의 ID field (Head) 를 클릭하면 다시 Dicom Study data 전체가 출력

### Output
- Dicom Study Data
  ![image](https://github.com/hsskia/unity_task/assets/162946806/54280279-258d-4b82-a868-51701fff2ed3)

- Dicom Series(Dicom Study ID 와 연동된 Series Data)
  - ID 16번을 클릭했을 때
  ![image](https://github.com/hsskia/unity_task/assets/162946806/78ecfdfa-c9a2-44e3-bc3d-a437e69f8656)

- 다시 ID 를 클릭했을 때(Study data로 원상 복구)
  ![image](https://github.com/hsskia/unity_task/assets/162946806/8c8b7344-3e7a-48f3-9751-fe0ad9ed4fe1)

2024-03-22 04:14 UTC, hsskia commented
Project open 하실 때 Issue 3 에 있는 [comment](https://github.com/hsskia/unity_task/issues/3#issuecomment-2014321425) 참고해주세요

2024-03-22 05:37 UTC, hyunheeskia requested changes

2024-03-22 05:37 UTC, hyunheeskia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +    public GameObject study_scrollview;
모든 구성요소를 Gameobject 라는 data type 으로 사용하셨는데,
Unity 에서 제공하는 UI 요소들에는 여러 종류의 타입이 있습니다.
검색해보시고 Gameobject 보다 좀 더 제한된 data type 으로 교체해주세요.
다른 변수들도 마찬가지입니다.

2024-03-22 06:18 UTC, hsskia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +    public GameObject study_scrollview;
- GameObject 만을 data type 으로 사용했을 때 scripts 에서 작성한 변수에 object 를 잘못 할당할 수 있습니다.
- Data type 의 범위를 좁혀서 사용하고자 하는 attributes 를 더 간단하게 사용할 수 있습니다.

2024-03-25 02:10 UTC, ChoiSieun1 requested changes

2024-03-25 02:10 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/dicom_tableview.cs
> +                result2 += $"{property.Name}: {val} \n";
result 와 result2 의 차이가 혹시 무엇일까요?
어딘가에 사용되는 text 인지 좀 더 정확하게 명시하면 좋을 듯 합니다~

예) result -> seriesText 라던가..?

2024-03-25 02:38 UTC, hsskia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +                result2 += $"{property.Name}: {val} \n";
result 는 기존에 step 1 과제에서 출력하려했던 dicom series 의 제목 부분인데 현재는 굳이 출력하지 않아서 제거했고 dicom series data 를 직접적으로 출력하는 result2 변수명은 `series_value` 로 좀 더 정확하게 명시했습니다!

2024-03-25 04:20 UTC, ChoiSieun1 approved these changes

2024-03-25 06:22 UTC, hyunheeskia requested changes

2024-03-25 06:22 UTC, hyunheeskia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +            GameObject new_row = (GameObject) Instantiate(row_content, scrollview_content.transform);
코드를 봤을 때 row_content 가
```
Gameobject
- ID Button
- name_text
- ...
```
이러한 형태로 고정인것같은데,
Gameobject 타입 대신
저러한 형태를 가진, Monbehavior를 상속하는 class로 만들면
훨씬 간편하게 사용할 수 있습니다.

2024-03-26 01:21 UTC, DaesooYoon-Skia requested changes

2024-03-26 01:21 UTC, DaesooYoon-Skia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +    void Add_DicomSeries_Rows(JArray data)
naming convention 통일합시다... 
맨 위에는 snake case, 
바로 위는 camel case, 
여기는... 혼합...

2024-03-26 01:26 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/dicom_tableview.cs
> +    void Add_DicomSeries_Rows(JArray data)
JObject 나 JArray 를 dicomStudy, dicomSeries 로 변경해주세요~

2024-03-26 01:27 UTC, ChoiSieun1 commented on Task1/Assets/Scripts/dicom_tableview.cs
> +    void Add_DicomSeries_Rows(JArray data)
Orm.cs 를 활용하시면 됩니다.

2024-03-26 02:35 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        for (int i = 1; i < childObject.Length; i++){
보통 0부터 시작하는데 1부터 시작하는 이유를 알 수 있을까요?

2024-03-26 02:47 UTC, hsskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        for (int i = 1; i < childObject.Length; i++){
해당 for 문은 table 의 RowContent 에 접근해서 series 데이터와 일치하는 studyID를 가지고 있는 study 데이터만 visibility 를 활성화하기 위함인데 index 0 은 필요한 데이터가 아닌 study 데이터 전체를 포함하는 Content 이기 때문에 1부터 접근했습니다.

2024-03-26 06:03 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        for (int i = 1; i < childObject.Length; i++){
0번은 study 이고 1번부터가 series 라는 말씀이시죠?
이런 경우는 유추하기 어렵기 때문에 주석을 달아주시면 좋을것같습니다!

2024-03-26 06:19 UTC, hsskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +        for (int i = 1; i < childObject.Length; i++){
0번은 전체 study data, 1번부터는 study data 의 각 행(행 하나)을 나타냅니다. 
series data 를 출력할 때는 전체 study data 가 아니라 현재 series data 가 표현하고 있는 studyID 에 해당하는 study data 만 활성화 된 상태로 놔둘 것이기 때문에 전체 데이터에는 접근할 필요가 없어 1번부터 시작했습니다.

2024-03-27 01:09 UTC, hyunheeskia approved these changes

2024-03-27 06:04 UTC, ChoiSieun1 approved these changes

2024-03-27 06:23 UTC, YunKeonTeck approved these changes

2024-03-27 06:23 UTC, YunKeonTeck approved these changes

2024-03-27 07:04 UTC, merged