Keyword 를 검색하고 Filtering 된 Dicom Data 들만 UI 에 출력하기
hsskia/unity_task pull request #6
Opened 2024-03-20 02:14 UTC by hsskia

close #5

### Issue
- 키워드를 입력 받고 입력된 키워드에 일치하는 Dicom Data 들을 출력하기

### Process
- 버튼과 Input Fileld 를 통해 입력 받은 키워드가 잘 출력되는지 확인
- 해당 키워드가 포함된 Dicom Data 를 필터링 하고 결과 콘솔에 출력
- 필터링 된 Dicom Data 만 Visible 하도록 Visibility 수정

2024-03-22 04:28 UTC, hsskia commented
Project open 하실 때 Issue 3 에 있는 [comment](https://github.com/hsskia/unity_task/issues/3#issuecomment-2014321425) 참고해주세요

2024-03-22 07:14 UTC, hsskia commented
### Data Type
- 모든 변수의 data type 을 GameObject 로 통일한다면 코드를 작성할 때는 편하겠지만 결국 변수에 object 를 할당할 때 실수 할 가능성이 존재한다.
  - ex) Text object 가 들어가야하는데 Button object 를 할당시켰을 때 둘 다 GameObject 이기 때문에 스크립트 상에서는 오류가 나지 않지만 원하는 기능이 제대로 구현되지 않을 수 있다.

- type 범위를 좁게 함으로써 사용하고자 하는 attibutes 를 더 간단히 사용할 수 있다.
  - case 1) GameObject 일 때 text 에 접근
    - `obj.GetComponent<Text>().text;`
  - case 2) Text 일 때 text 에 접근
    - `obj.text;`

2024-03-26 06:35 UTC, alkee-skia reviewed
코딩하면서 코드에대한 고민을 조금씩 더 해봐주시면 좋겠습니다. 일관적인 style 을 유지하고 있는지, 명료한 표현을 유지하고있는지 등등이요.

2024-03-26 06:35 UTC, alkee-skia commented on Task1/Assets/Scripts/dicom_data_search.cs
> +    public ScrollRect study_scrollview;
이 class 외부에서 사용하지 않는 field, function 이라면 모두 private 을 사용해야 합니다. unity insepctor 로 설정이 필요하면 [SerializeFieldAttribute](https://docs.unity3d.com/ScriptReference/SerializeField.html) 를 사용하시면 됩니다.

모든 member 들을 private 으로 바꾸어보시고 오류(build error)가 발생하면 올바르게 사용하고있는 것인지 생각도 해보시고, 필요하다면 그때 public 으로 바꾸어 보시는것을 추천합니다.

2024-03-26 06:35 UTC, alkee-skia commented on Task1/Assets/Scripts/dicom_data_search.cs
> +    string dicom_url = "http://10.10.20.173:5080/v2/Dicom/";
변경되지 않는 정보라면 `const` keyword 를 사용하실 수 있습니다.

2024-03-26 06:35 UTC, alkee-skia commented on Task1/Assets/Scripts/dicom_data_search.cs
> +        if (study_id == "ID"){
vscode 의 설정에 저장전에 formatting 하도록 하는 설정이 있을겁니다. 설정해두시고 사용해주세요

2024-03-26 06:35 UTC, alkee-skia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +    public void on_click()
이름짓기에 대한 일관성이 필요할 것 같습니다. 변수들을 lower_case 로 작성한것 같은데, 함수들은 PascalCase 와 밑줄을 포함한 네이밍등 일관성없이 사용되고있습니다.

2024-03-26 06:35 UTC, alkee-skia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +    // Series 데이터 항목 삭제
함수이름이나 코드를 보고 즉시 알 수 있는 내용이라면 굳이 주석이 필요하지 않습니다.

2024-03-26 06:35 UTC, alkee-skia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +            // 원본 제외 복사한 항목 모두 삭제
함수 내 주석은, 코드를 그대로 설명하기보다 왜 이러한 코드가 되었는지를 설명하는것이 좋습니다. 예를들면 왜 i 가 1부터 시작하는지. "Clone" 이라는 이름을 왜 포함하는지와 같이요

2024-03-26 06:35 UTC, alkee-skia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +                    child_object2[j].gameObject.SetActive(true);
if 문은 최대한 줄일수록 좋습니다. nested 되어있다면 더더욱이요.

예를들면,

```cs
child_object2[j].gameObject.SetActive(check);
if (check) continue;

...
```
와 같이 nested 를 피할수도 있습니다.

2024-03-26 06:40 UTC, hsskia commented on Task1/Assets/Scripts/dicom_tableview.cs
> +                    child_object2[j].gameObject.SetActive(true);
과장님 피드백 정말 감사합니다!해당 부분 보완하겠습니다

2024-03-28 06:18 UTC, hyunheeskia commented
![image](https://github.com/hsskia/unity_task/assets/134245511/8b6d09d2-4050-47fe-af5b-ee4726174f80)

사용하지 않는 using 의 경우 이렇게 흐린 색으로 표시됩니다.
사용하지 않는 using은 삭제해주세요.

2024-03-28 06:24 UTC, hyunheeskia requested changes

2024-03-28 06:24 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomDataSearch.cs
이 class 의 경우 기존에 있었던 DicomTableView 와 굉장히 유사한 구조로 보입니다.
실제로 이전 과제에서 만들었던 것과 결과 이미지도 유사하고요.
새로운 class를 만드는 방식이 아닌,
기존에 있었던 DicomTableView 를 보완하는 방식으로 진행해주세요.

2024-03-29 01:04 UTC, hyunheeskia commented
![image](https://github.com/hsskia/unity_task/assets/134245511/8c75356d-f6a1-4c42-a48e-46e3068e4eb3)

dicom study id 를 클릭하면 dicom series 가 출력되는 화면으로 전환되면서
play 를 종료하고 재시작하지 않으면 처음 화면처럼 검색창이 있는 화면으로 돌아가는게 불가능합니다.
어떻게 하면 좀 더 사용하기 편하게 만들 수 있는지 생각해보고 수정해주세요.

2024-03-29 01:17 UTC, hsskia commented
현재는 ID 번호(숫자)를 눌렀을 때 series  data 로 이동하고 ID(열 이름) 문자를 클릭했을 때 다시 study data 가 출력되는 처음 화면으로 돌아가도록 동작하고 있습니다.
해당 부분이 직관적이지 않다 라는 피드백을 주셔서 개선시켜보겠습니다!

2024-03-29 09:07 UTC, hyunheeskia requested changes

2024-03-29 09:07 UTC, hyunheeskia commented on Task1/Assets/Scripts/DicomTableview.cs
> +    public void OnClickId()
이 동작이 이제는 id 를 클릭했을때의 동작이 아니게 된거죠?
그렇다면 네이밍도 그에 맞게 바꿔주세요.

2024-04-02 01:24 UTC, ChoiSieun1 approved these changes

2024-04-02 01:51 UTC, hyunheeskia approved these changes

2024-04-04 02:35 UTC, YunKeonTeck approved these changes

2024-04-04 02:36 UTC, merged